
# Define variables
# NOTE: executable should be a full path
LOGS_DIR=/fast/najroldi/logs/llm
executable=/home/najroldi/llm_pretrain/cluster/condor/multi_gpu/run.sh

# Job specific vars
config=config/pythia_7B.yaml
n_jobs=1

# Args
arguments = $(config) $(Process)

# Logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Specs
request_memory = 1000000
request_cpus = 96
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3") && (TARGET.Machine != "i105.internal.cluster.is.localnet")

queue $(n_jobs)
